-- 1. Kullanıcılar Tablosu
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK(role IN ('student', 'teacher')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Sınıflar Tablosu
CREATE TABLE IF NOT EXISTS classrooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  code TEXT UNIQUE NOT NULL,
  teacher_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Sınıf Üyeleri Tablosu
CREATE TABLE IF NOT EXISTS classroom_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id BIGINT NOT NULL REFERENCES classrooms(id) ON DELETE CASCADE,
  student_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(classroom_id, student_id)
);

-- 4. Sorular Tablosu
CREATE TABLE IF NOT EXISTS questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  image_path TEXT NOT NULL,
  subject TEXT NOT NULL,
  topic TEXT DEFAULT '',
  difficulty TEXT DEFAULT 'orta',
  notes TEXT DEFAULT '',
  tags TEXT DEFAULT '[]',
  ai_solution TEXT DEFAULT '',
  ai_topic TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Öğretmen Yorumları Tablosu
CREATE TABLE IF NOT EXISTS teacher_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  student_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  comment TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Depolama için "questions" adlı bucket oluşturulması gereklidir.
-- (Bunu Supabase panelinden "Storage" kısmından manuel oluşturabilir veya alttaki SQL ile yapabilirsiniz.)
INSERT INTO storage.buckets (id, name, public) VALUES ('questions', 'questions', true) ON CONFLICT DO NOTHING;
